# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Postcards < Formula
  desc "Tool for creating digital versions of physical postcards"
  homepage "https://dotpostcards.org/cli/postcards"
  version "0.11.1"
  license "MIT"

  depends_on "exiv2"
  depends_on "webp"
  depends_on :macos

  on_macos do
    url "https://github.com/dotpostcard/postcards-go/releases/download/0.11.1/postcards-0.11.1-macOS-universal.zip"
    sha256 "0bfb4980bb8834d643ae05ab4a3700fa0f54b3beb31ab64643c3091abe080b64"

    def install
      bin.install "postcards"
    end
  end

  resource("hello.postcard") do
    url "https://github.com/dotpostcard/postcards-go/blob/1484f9c8a20f862fa1edc502b922eeb5050b6091/fixtures/hello.postcard?raw=true"
    sha256 "278ba622122f08e218c929a46ae056dc074a42f12514516eb980587ab1d3ae39"
  end

  test do
    resource("hello.postcard").stage do
      expected_start = "Postcard:   hello.postcard\nSize:       881.3 KiB\n"
      actual_output = shell_output("#{bin}/postcards info hello.postcard")
      assert actual_output.start_with?(expected_start)
    end
  end
end
